version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3315:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

volumes:
  mysql_data:
