apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: staging-env
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
              subPath: mysql
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rails6
  name: rails6-deployment
  namespace: staging-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails6
  template:
    metadata:
      labels:
        app: rails6
    spec:
      containers:
      - image: chrisdebruin/rails6:master
        name: rails6
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /status
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 30
        env:
        - name: DATABASE_PASSWORD
          value: ~
        - name: DATABASE_HOST
          value: mysql-cluster-ip-service
        - name: RAILS_ENV
          value: staging
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-master-key
              key: RAILS_MASTER_KEY
