---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: staging-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: eu.gcr.io/cloud-run-238617/rails6:master
        name: web
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 200m
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /status
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 30
        env:
        - name: DATABASE_PASSWORD
          value: ~
        - name: DATABASE_HOST
          value: mysql-cluster-ip-service
        - name: RAILS_ENV
          value: staging
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: master-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-deployment
  namespace: staging-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delayed-job
  template:
    metadata:
      labels:
        app: delayed-job
    spec:
      containers:
      - image: eu.gcr.io/cloud-run-238617/rails6:master
        name: delayed-job
        imagePullPolicy: Always
        command: ["bundle", "exec", "rails", "jobs:work"]
        env:
        - name: DATABASE_PASSWORD
          value: ~
        - name: DATABASE_HOST
          value: mysql-cluster-ip-service
        - name: RAILS_ENV
          value: staging
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: master-key
