apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rails6-ingress
  namespace: staging-env
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: rails6-service
              servicePort: 80
