apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: staging-env
spec:
  tls:
  - hosts:
    - k8s.flexcoder.nl
    secretName: flexcoder-secret
  rules:
    - host: k8s.flexcoder.nl
      http:
        paths:
          - path: /*
            backend:
              serviceName: web-service
              servicePort: 80
