apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: staging-env
spec:
  completions: 1
  template:
    metadata:
      name: db-migrate
    spec:
      containers:
      - name: db-migrate
        image: eu.gcr.io/cloud-run-238617/rails6:master
        command: ["bundle", "exec", "rails", "db:prepare"]
        imagePullPolicy: Always
        env:
        - name: DATABASE_PASSWORD
          value: ~
        - name: DATABASE_HOST
          value: mysql-cluster-ip-service
        - name: RAILS_ENV
          value: staging
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: master-key
      restartPolicy: Never
